/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "Messages.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_ACKsliceMessage_H_
#define	_ACKsliceMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ACKsliceMessage */
typedef struct ACKsliceMessage {
	long	 frameID;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ACKsliceMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ACKsliceMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _ACKsliceMessage_H_ */
#include <asn_internal.h>
