/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "Messages.asn1"
 * 	`asn1c -fnative-types`
 */

#include "CooperatorInfo.h"

static asn_TYPE_member_t asn_MBR_CooperatorInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CooperatorInfo, coopId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"coopId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CooperatorInfo, ipAddress),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ipAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CooperatorInfo, port),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"port"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CooperatorInfo, status),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CoopStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"status"
		},
};
static ber_tlv_tag_t asn_DEF_CooperatorInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CooperatorInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* coopId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ipAddress */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* port */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* status */
};
static asn_SEQUENCE_specifics_t asn_SPC_CooperatorInfo_specs_1 = {
	sizeof(struct CooperatorInfo),
	offsetof(struct CooperatorInfo, _asn_ctx),
	asn_MAP_CooperatorInfo_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CooperatorInfo = {
	"CooperatorInfo",
	"CooperatorInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CooperatorInfo_tags_1,
	sizeof(asn_DEF_CooperatorInfo_tags_1)
		/sizeof(asn_DEF_CooperatorInfo_tags_1[0]), /* 1 */
	asn_DEF_CooperatorInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_CooperatorInfo_tags_1)
		/sizeof(asn_DEF_CooperatorInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CooperatorInfo_1,
	4,	/* Elements count */
	&asn_SPC_CooperatorInfo_specs_1	/* Additional specs */
};

