/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "Messages.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_Coordinate_H_
#define	_Coordinate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Coordinate */
typedef struct Coordinate {
	long	 xCoordinate;
	long	 yCoordinate;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Coordinate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Coordinate;

#ifdef __cplusplus
}
#endif

#endif	/* _Coordinate_H_ */
#include <asn_internal.h>
