/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "Messages.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_DataATCMessage_H_
#define	_DataATCMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeReal.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DataATCMessage */
typedef struct DataATCMessage {
	long	 frameID;
	long	 blockNumber;
	long	 numBlocks;
	double	 detTime;
	double	 descTime;
	double	 kencTime;
	double	 fencTime;
	double	 txTime;
	long	 numFeat;
	long	 numKpts;
	OCTET_STRING_t	 featuresData;
	OCTET_STRING_t	 kptsData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataATCMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataATCMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _DataATCMessage_H_ */
#include <asn_internal.h>
