/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "Messages.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_DescriptorTypes_H_
#define	_DescriptorTypes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DescriptorTypes {
	DescriptorTypes_sift	= 0,
	DescriptorTypes_surf	= 1,
	DescriptorTypes_brief	= 2,
	DescriptorTypes_brisk	= 3,
	DescriptorTypes_orb	= 4,
	DescriptorTypes_freak	= 5
} e_DescriptorTypes;

/* DescriptorTypes */
typedef long	 DescriptorTypes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DescriptorTypes;
asn_struct_free_f DescriptorTypes_free;
asn_struct_print_f DescriptorTypes_print;
asn_constr_check_f DescriptorTypes_constraint;
ber_type_decoder_f DescriptorTypes_decode_ber;
der_type_encoder_f DescriptorTypes_encode_der;
xer_type_decoder_f DescriptorTypes_decode_xer;
xer_type_encoder_f DescriptorTypes_encode_xer;
per_type_decoder_f DescriptorTypes_decode_uper;
per_type_encoder_f DescriptorTypes_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DescriptorTypes_H_ */
#include <asn_internal.h>
