/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "Messages.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_DetectorTypes_H_
#define	_DetectorTypes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DetectorTypes {
	DetectorTypes_fast	= 0,
	DetectorTypes_star	= 1,
	DetectorTypes_sift	= 2,
	DetectorTypes_surf	= 3,
	DetectorTypes_orb	= 4,
	DetectorTypes_brisk	= 5,
	DetectorTypes_mser	= 6
} e_DetectorTypes;

/* DetectorTypes */
typedef long	 DetectorTypes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DetectorTypes;
asn_struct_free_f DetectorTypes_free;
asn_struct_print_f DetectorTypes_print;
asn_constr_check_f DetectorTypes_constraint;
ber_type_decoder_f DetectorTypes_decode_ber;
der_type_encoder_f DetectorTypes_encode_der;
xer_type_decoder_f DetectorTypes_decode_xer;
xer_type_encoder_f DetectorTypes_encode_xer;
per_type_decoder_f DetectorTypes_decode_uper;
per_type_encoder_f DetectorTypes_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DetectorTypes_H_ */
#include <asn_internal.h>
