/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "Messages.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_StartCTAMessage_H_
#define	_StartCTAMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* StartCTAMessage */
typedef struct StartCTAMessage {
	long	 framesPerSecond;
	long	 qualityFactor;
	long	 frameHeight;
	long	 frameWidth;
	long	 numSlices;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StartCTAMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StartCTAMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _StartCTAMessage_H_ */
#include <asn_internal.h>
