/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "WiFiUDP_asn1defs.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_Address_H_
#define	_Address_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Address */
typedef unsigned long	 Address_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Address;
asn_struct_free_f Address_free;
asn_struct_print_f Address_print;
asn_constr_check_f Address_constraint;
ber_type_decoder_f Address_decode_ber;
der_type_encoder_f Address_encode_der;
xer_type_decoder_f Address_decode_xer;
xer_type_encoder_f Address_encode_xer;
per_type_decoder_f Address_decode_uper;
per_type_encoder_f Address_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Address_H_ */
#include <asn_internal.h>
