/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "WiFiUDP_asn1defs.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_MessageTypes_H_
#define	_MessageTypes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MessageTypes {
	MessageTypes_receptionReport	= 0,
	MessageTypes_receptionReportRequest	= 1,
	MessageTypes_dataMsg	= 2,
	MessageTypes_connectMsg	= 3
} e_MessageTypes;

/* MessageTypes */
typedef long	 MessageTypes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageTypes;
asn_struct_free_f MessageTypes_free;
asn_struct_print_f MessageTypes_print;
asn_constr_check_f MessageTypes_constraint;
ber_type_decoder_f MessageTypes_decode_ber;
der_type_encoder_f MessageTypes_encode_der;
xer_type_decoder_f MessageTypes_decode_xer;
xer_type_encoder_f MessageTypes_encode_xer;
per_type_decoder_f MessageTypes_decode_uper;
per_type_encoder_f MessageTypes_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageTypes_H_ */
#include <asn_internal.h>
