/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "WiFiUDP_asn1defs.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_Packet_H_
#define	_Packet_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PacketHeader.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Packet */
typedef struct Packet {
	PacketHeader_t	 header;
	OCTET_STRING_t	 data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Packet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Packet;

#ifdef __cplusplus
}
#endif

#endif	/* _Packet_H_ */
#include <asn_internal.h>
