/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "WiFiUDP_asn1defs.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_ReceptionReportRequestMessage_H_
#define	_ReceptionReportRequestMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReceptionReportRequestMessage */
typedef struct ReceptionReportRequestMessage {
	long	 messageID;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReceptionReportRequestMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReceptionReportRequestMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _ReceptionReportRequestMessage_H_ */
#include <asn_internal.h>
