/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "VSNTestBed"
 * 	found in "WiFiUDP_asn1defs.asn1"
 * 	`asn1c -fnative-types`
 */

#include "ReceptionReportMessage.h"

static asn_TYPE_member_t asn_MBR_droppedPackets_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_droppedPackets_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_droppedPackets_specs_3 = {
	sizeof(struct droppedPackets),
	offsetof(struct droppedPackets, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_droppedPackets_3 = {
	"droppedPackets",
	"droppedPackets",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_droppedPackets_tags_3,
	sizeof(asn_DEF_droppedPackets_tags_3)
		/sizeof(asn_DEF_droppedPackets_tags_3[0]) - 1, /* 1 */
	asn_DEF_droppedPackets_tags_3,	/* Same as above */
	sizeof(asn_DEF_droppedPackets_tags_3)
		/sizeof(asn_DEF_droppedPackets_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_droppedPackets_3,
	1,	/* Single element */
	&asn_SPC_droppedPackets_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ReceptionReportMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReceptionReportMessage, mode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReceptionReportModes,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReceptionReportMessage, droppedPackets),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_droppedPackets_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"droppedPackets"
		},
};
static ber_tlv_tag_t asn_DEF_ReceptionReportMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ReceptionReportMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* droppedPackets */
};
static asn_SEQUENCE_specifics_t asn_SPC_ReceptionReportMessage_specs_1 = {
	sizeof(struct ReceptionReportMessage),
	offsetof(struct ReceptionReportMessage, _asn_ctx),
	asn_MAP_ReceptionReportMessage_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ReceptionReportMessage = {
	"ReceptionReportMessage",
	"ReceptionReportMessage",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ReceptionReportMessage_tags_1,
	sizeof(asn_DEF_ReceptionReportMessage_tags_1)
		/sizeof(asn_DEF_ReceptionReportMessage_tags_1[0]), /* 1 */
	asn_DEF_ReceptionReportMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReceptionReportMessage_tags_1)
		/sizeof(asn_DEF_ReceptionReportMessage_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ReceptionReportMessage_1,
	2,	/* Elements count */
	&asn_SPC_ReceptionReportMessage_specs_1	/* Additional specs */
};

